package constants

import "fghpdf.com/mysqlMigration/errors"

type Charset struct {
	Id        uint
	Name      string
	Collation string
	IsDefault bool
	MaxLen    uint
}

var codeToCharsetMap = map[uint64]Charset{
	32: {
		Id:        32,
		Name:      "armscii8",
		Collation: "armscii8_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	64: {
		Id:        64,
		Name:      "armscii8",
		Collation: "armscii8_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	11: {
		Id:        11,
		Name:      "ascii",
		Collation: "ascii_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	65: {
		Id:        65,
		Name:      "ascii",
		Collation: "ascii_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	1: {
		Id:        1,
		Name:      "big5",
		Collation: "big5_chinese_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	84: {
		Id:        84,
		Name:      "big5",
		Collation: "big5_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	63: {
		Id:        63,
		Name:      "binary",
		Collation: "binary",
		IsDefault: true,
		MaxLen:    1,
	},
	26: {
		Id:        26,
		Name:      "cp1250",
		Collation: "cp1250_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	34: {
		Id:        34,
		Name:      "cp1250",
		Collation: "cp1250_czech_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	44: {
		Id:        44,
		Name:      "cp1250",
		Collation: "cp1250_croatian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	66: {
		Id:        66,
		Name:      "cp1250",
		Collation: "cp1250_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	99: {
		Id:        99,
		Name:      "cp1250",
		Collation: "cp1250_polish_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	14: {
		Id:        14,
		Name:      "cp1251",
		Collation: "cp1251_bulgarian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	23: {
		Id:        23,
		Name:      "cp1251",
		Collation: "cp1251_ukrainian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	50: {
		Id:        50,
		Name:      "cp1251",
		Collation: "cp1251_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	51: {
		Id:        51,
		Name:      "cp1251",
		Collation: "cp1251_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	52: {
		Id:        52,
		Name:      "cp1251",
		Collation: "cp1251_general_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	57: {
		Id:        57,
		Name:      "cp1256",
		Collation: "cp1256_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	67: {
		Id:        67,
		Name:      "cp1256",
		Collation: "cp1256_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	29: {
		Id:        29,
		Name:      "cp1257",
		Collation: "cp1257_lithuanian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	58: {
		Id:        58,
		Name:      "cp1257",
		Collation: "cp1257_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	59: {
		Id:        59,
		Name:      "cp1257",
		Collation: "cp1257_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	4: {
		Id:        4,
		Name:      "cp850",
		Collation: "cp850_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	80: {
		Id:        80,
		Name:      "cp850",
		Collation: "cp850_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	40: {
		Id:        40,
		Name:      "cp852",
		Collation: "cp852_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	81: {
		Id:        81,
		Name:      "cp852",
		Collation: "cp852_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	36: {
		Id:        36,
		Name:      "cp866",
		Collation: "cp866_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	68: {
		Id:        68,
		Name:      "cp866",
		Collation: "cp866_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	95: {
		Id:        95,
		Name:      "cp932",
		Collation: "cp932_japanese_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	96: {
		Id:        96,
		Name:      "cp932",
		Collation: "cp932_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	3: {
		Id:        3,
		Name:      "dec8",
		Collation: "dec8_swedish_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	69: {
		Id:        69,
		Name:      "dec8",
		Collation: "dec8_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	97: {
		Id:        97,
		Name:      "eucjpms",
		Collation: "eucjpms_japanese_ci",
		IsDefault: true,
		MaxLen:    3,
	},
	98: {
		Id:        98,
		Name:      "eucjpms",
		Collation: "eucjpms_bin",
		IsDefault: false,
		MaxLen:    3,
	},
	19: {
		Id:        19,
		Name:      "euckr",
		Collation: "euckr_korean_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	85: {
		Id:        85,
		Name:      "euckr",
		Collation: "euckr_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	24: {
		Id:        24,
		Name:      "gb2312",
		Collation: "gb2312_chinese_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	86: {
		Id:        86,
		Name:      "gb2312",
		Collation: "gb2312_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	28: {
		Id:        28,
		Name:      "gbk",
		Collation: "gbk_chinese_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	87: {
		Id:        87,
		Name:      "gbk",
		Collation: "gbk_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	92: {
		Id:        92,
		Name:      "geostd8",
		Collation: "geostd8_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	93: {
		Id:        93,
		Name:      "geostd8",
		Collation: "geostd8_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	25: {
		Id:        25,
		Name:      "greek",
		Collation: "greek_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	70: {
		Id:        70,
		Name:      "greek",
		Collation: "greek_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	16: {
		Id:        16,
		Name:      "hebrew",
		Collation: "hebrew_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	71: {
		Id:        71,
		Name:      "hebrew",
		Collation: "hebrew_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	6: {
		Id:        6,
		Name:      "hp8",
		Collation: "hp8_english_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	72: {
		Id:        72,
		Name:      "hp8",
		Collation: "hp8_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	37: {
		Id:        37,
		Name:      "keybcs2",
		Collation: "keybcs2_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	73: {
		Id:        73,
		Name:      "keybcs2",
		Collation: "keybcs2_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	7: {
		Id:        7,
		Name:      "koi8r",
		Collation: "koi8r_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	74: {
		Id:        74,
		Name:      "koi8r",
		Collation: "koi8r_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	22: {
		Id:        22,
		Name:      "koi8u",
		Collation: "koi8u_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	75: {
		Id:        75,
		Name:      "koi8u",
		Collation: "koi8u_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	5: {
		Id:        5,
		Name:      "latin1",
		Collation: "latin1_german1_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	8: {
		Id:        8,
		Name:      "latin1",
		Collation: "latin1_swedish_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	15: {
		Id:        15,
		Name:      "latin1",
		Collation: "latin1_danish_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	31: {
		Id:        31,
		Name:      "latin1",
		Collation: "latin1_german2_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	47: {
		Id:        47,
		Name:      "latin1",
		Collation: "latin1_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	48: {
		Id:        48,
		Name:      "latin1",
		Collation: "latin1_general_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	49: {
		Id:        49,
		Name:      "latin1",
		Collation: "latin1_general_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	94: {
		Id:        94,
		Name:      "latin1",
		Collation: "latin1_spanish_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	2: {
		Id:        2,
		Name:      "latin2",
		Collation: "latin2_czech_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	9: {
		Id:        9,
		Name:      "latin2",
		Collation: "latin2_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	21: {
		Id:        21,
		Name:      "latin2",
		Collation: "latin2_hungarian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	27: {
		Id:        27,
		Name:      "latin2",
		Collation: "latin2_croatian_ci",
		IsDefault: false,
		MaxLen:    1,
	},
	77: {
		Id:        77,
		Name:      "latin2",
		Collation: "latin2_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	30: {
		Id:        30,
		Name:      "latin5",
		Collation: "latin5_turkish_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	78: {
		Id:        78,
		Name:      "latin5",
		Collation: "latin5_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	20: {
		Id:        20,
		Name:      "latin7",
		Collation: "latin7_estonian_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	41: {
		Id:        41,
		Name:      "latin7",
		Collation: "latin7_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	42: {
		Id:        42,
		Name:      "latin7",
		Collation: "latin7_general_cs",
		IsDefault: false,
		MaxLen:    1,
	},
	79: {
		Id:        79,
		Name:      "latin7",
		Collation: "latin7_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	38: {
		Id:        38,
		Name:      "macce",
		Collation: "macce_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	43: {
		Id:        43,
		Name:      "macce",
		Collation: "macce_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	39: {
		Id:        39,
		Name:      "macroman",
		Collation: "macroman_general_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	53: {
		Id:        53,
		Name:      "macroman",
		Collation: "macroman_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	13: {
		Id:        13,
		Name:      "sjis",
		Collation: "sjis_japanese_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	88: {
		Id:        88,
		Name:      "sjis",
		Collation: "sjis_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	10: {
		Id:        10,
		Name:      "swe7",
		Collation: "swe7_swedish_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	82: {
		Id:        82,
		Name:      "swe7",
		Collation: "swe7_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	18: {
		Id:        18,
		Name:      "tis620",
		Collation: "tis620_thai_ci",
		IsDefault: true,
		MaxLen:    1,
	},
	89: {
		Id:        89,
		Name:      "tis620",
		Collation: "tis620_bin",
		IsDefault: false,
		MaxLen:    1,
	},
	35: {
		Id:        35,
		Name:      "ucs2",
		Collation: "ucs2_general_ci",
		IsDefault: true,
		MaxLen:    2,
	},
	90: {
		Id:        90,
		Name:      "ucs2",
		Collation: "ucs2_bin",
		IsDefault: false,
		MaxLen:    2,
	},
	128: {
		Id:        128,
		Name:      "ucs2",
		Collation: "ucs2_unicode_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	129: {
		Id:        129,
		Name:      "ucs2",
		Collation: "ucs2_icelandic_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	130: {
		Id:        130,
		Name:      "ucs2",
		Collation: "ucs2_latvian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	131: {
		Id:        131,
		Name:      "ucs2",
		Collation: "ucs2_romanian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	132: {
		Id:        132,
		Name:      "ucs2",
		Collation: "ucs2_slovenian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	133: {
		Id:        133,
		Name:      "ucs2",
		Collation: "ucs2_polish_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	134: {
		Id:        134,
		Name:      "ucs2",
		Collation: "ucs2_estonian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	135: {
		Id:        135,
		Name:      "ucs2",
		Collation: "ucs2_spanish_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	136: {
		Id:        136,
		Name:      "ucs2",
		Collation: "ucs2_swedish_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	137: {
		Id:        137,
		Name:      "ucs2",
		Collation: "ucs2_turkish_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	138: {
		Id:        138,
		Name:      "ucs2",
		Collation: "ucs2_czech_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	139: {
		Id:        139,
		Name:      "ucs2",
		Collation: "ucs2_danish_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	140: {
		Id:        140,
		Name:      "ucs2",
		Collation: "ucs2_lithuanian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	141: {
		Id:        141,
		Name:      "ucs2",
		Collation: "ucs2_slovak_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	142: {
		Id:        142,
		Name:      "ucs2",
		Collation: "ucs2_spanish2_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	143: {
		Id:        143,
		Name:      "ucs2",
		Collation: "ucs2_roman_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	144: {
		Id:        144,
		Name:      "ucs2",
		Collation: "ucs2_persian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	145: {
		Id:        145,
		Name:      "ucs2",
		Collation: "ucs2_esperanto_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	146: {
		Id:        146,
		Name:      "ucs2",
		Collation: "ucs2_hungarian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	147: {
		Id:        147,
		Name:      "ucs2",
		Collation: "ucs2_sinhala_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	148: {
		Id:        148,
		Name:      "ucs2",
		Collation: "ucs2_german2_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	149: {
		Id:        149,
		Name:      "ucs2",
		Collation: "ucs2_croatian_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	150: {
		Id:        150,
		Name:      "ucs2",
		Collation: "ucs2_unicode_520_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	151: {
		Id:        151,
		Name:      "ucs2",
		Collation: "ucs2_vietnamese_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	159: {
		Id:        159,
		Name:      "ucs2",
		Collation: "ucs2_general_mysql500_ci",
		IsDefault: false,
		MaxLen:    2,
	},
	12: {
		Id:        12,
		Name:      "ujis",
		Collation: "ujis_japanese_ci",
		IsDefault: true,
		MaxLen:    3,
	},
	91: {
		Id:        91,
		Name:      "ujis",
		Collation: "ujis_bin",
		IsDefault: false,
		MaxLen:    3,
	},
	54: {
		Id:        54,
		Name:      "utf16",
		Collation: "utf16_general_ci",
		IsDefault: true,
		MaxLen:    4,
	},
	55: {
		Id:        55,
		Name:      "utf16",
		Collation: "utf16_bin",
		IsDefault: false,
		MaxLen:    4,
	},
	101: {
		Id:        101,
		Name:      "utf16",
		Collation: "utf16_unicode_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	102: {
		Id:        102,
		Name:      "utf16",
		Collation: "utf16_icelandic_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	103: {
		Id:        103,
		Name:      "utf16",
		Collation: "utf16_latvian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	104: {
		Id:        104,
		Name:      "utf16",
		Collation: "utf16_romanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	105: {
		Id:        105,
		Name:      "utf16",
		Collation: "utf16_slovenian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	106: {
		Id:        106,
		Name:      "utf16",
		Collation: "utf16_polish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	107: {
		Id:        107,
		Name:      "utf16",
		Collation: "utf16_estonian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	108: {
		Id:        108,
		Name:      "utf16",
		Collation: "utf16_spanish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	109: {
		Id:        109,
		Name:      "utf16",
		Collation: "utf16_swedish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	110: {
		Id:        110,
		Name:      "utf16",
		Collation: "utf16_turkish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	111: {
		Id:        111,
		Name:      "utf16",
		Collation: "utf16_czech_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	112: {
		Id:        112,
		Name:      "utf16",
		Collation: "utf16_danish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	113: {
		Id:        113,
		Name:      "utf16",
		Collation: "utf16_lithuanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	114: {
		Id:        114,
		Name:      "utf16",
		Collation: "utf16_slovak_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	115: {
		Id:        115,
		Name:      "utf16",
		Collation: "utf16_spanish2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	116: {
		Id:        116,
		Name:      "utf16",
		Collation: "utf16_roman_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	117: {
		Id:        117,
		Name:      "utf16",
		Collation: "utf16_persian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	118: {
		Id:        118,
		Name:      "utf16",
		Collation: "utf16_esperanto_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	119: {
		Id:        119,
		Name:      "utf16",
		Collation: "utf16_hungarian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	120: {
		Id:        120,
		Name:      "utf16",
		Collation: "utf16_sinhala_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	121: {
		Id:        121,
		Name:      "utf16",
		Collation: "utf16_german2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	122: {
		Id:        122,
		Name:      "utf16",
		Collation: "utf16_croatian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	123: {
		Id:        123,
		Name:      "utf16",
		Collation: "utf16_unicode_520_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	124: {
		Id:        124,
		Name:      "utf16",
		Collation: "utf16_vietnamese_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	56: {
		Id:        56,
		Name:      "utf16le",
		Collation: "utf16le_general_ci",
		IsDefault: true,
		MaxLen:    4,
	},
	62: {
		Id:        62,
		Name:      "utf16le",
		Collation: "utf16le_bin",
		IsDefault: false,
		MaxLen:    4,
	},
	60: {
		Id:        60,
		Name:      "utf32",
		Collation: "utf32_general_ci",
		IsDefault: true,
		MaxLen:    4,
	},
	61: {
		Id:        61,
		Name:      "utf32",
		Collation: "utf32_bin",
		IsDefault: false,
		MaxLen:    4,
	},
	160: {
		Id:        160,
		Name:      "utf32",
		Collation: "utf32_unicode_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	161: {
		Id:        161,
		Name:      "utf32",
		Collation: "utf32_icelandic_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	162: {
		Id:        162,
		Name:      "utf32",
		Collation: "utf32_latvian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	163: {
		Id:        163,
		Name:      "utf32",
		Collation: "utf32_romanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	164: {
		Id:        164,
		Name:      "utf32",
		Collation: "utf32_slovenian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	165: {
		Id:        165,
		Name:      "utf32",
		Collation: "utf32_polish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	166: {
		Id:        166,
		Name:      "utf32",
		Collation: "utf32_estonian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	167: {
		Id:        167,
		Name:      "utf32",
		Collation: "utf32_spanish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	168: {
		Id:        168,
		Name:      "utf32",
		Collation: "utf32_swedish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	169: {
		Id:        169,
		Name:      "utf32",
		Collation: "utf32_turkish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	170: {
		Id:        170,
		Name:      "utf32",
		Collation: "utf32_czech_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	171: {
		Id:        171,
		Name:      "utf32",
		Collation: "utf32_danish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	172: {
		Id:        172,
		Name:      "utf32",
		Collation: "utf32_lithuanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	173: {
		Id:        173,
		Name:      "utf32",
		Collation: "utf32_slovak_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	174: {
		Id:        174,
		Name:      "utf32",
		Collation: "utf32_spanish2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	175: {
		Id:        175,
		Name:      "utf32",
		Collation: "utf32_roman_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	176: {
		Id:        176,
		Name:      "utf32",
		Collation: "utf32_persian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	177: {
		Id:        177,
		Name:      "utf32",
		Collation: "utf32_esperanto_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	178: {
		Id:        178,
		Name:      "utf32",
		Collation: "utf32_hungarian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	179: {
		Id:        179,
		Name:      "utf32",
		Collation: "utf32_sinhala_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	180: {
		Id:        180,
		Name:      "utf32",
		Collation: "utf32_german2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	181: {
		Id:        181,
		Name:      "utf32",
		Collation: "utf32_croatian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	182: {
		Id:        182,
		Name:      "utf32",
		Collation: "utf32_unicode_520_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	183: {
		Id:        183,
		Name:      "utf32",
		Collation: "utf32_vietnamese_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	33: {
		Id:        33,
		Name:      "utf8",
		Collation: "utf8_general_ci",
		IsDefault: true,
		MaxLen:    3,
	},
	83: {
		Id:        83,
		Name:      "utf8",
		Collation: "utf8_bin",
		IsDefault: false,
		MaxLen:    3,
	},
	192: {
		Id:        192,
		Name:      "utf8",
		Collation: "utf8_unicode_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	193: {
		Id:        193,
		Name:      "utf8",
		Collation: "utf8_icelandic_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	194: {
		Id:        194,
		Name:      "utf8",
		Collation: "utf8_latvian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	195: {
		Id:        195,
		Name:      "utf8",
		Collation: "utf8_romanian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	196: {
		Id:        196,
		Name:      "utf8",
		Collation: "utf8_slovenian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	197: {
		Id:        197,
		Name:      "utf8",
		Collation: "utf8_polish_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	198: {
		Id:        198,
		Name:      "utf8",
		Collation: "utf8_estonian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	199: {
		Id:        199,
		Name:      "utf8",
		Collation: "utf8_spanish_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	200: {
		Id:        200,
		Name:      "utf8",
		Collation: "utf8_swedish_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	201: {
		Id:        201,
		Name:      "utf8",
		Collation: "utf8_turkish_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	202: {
		Id:        202,
		Name:      "utf8",
		Collation: "utf8_czech_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	203: {
		Id:        203,
		Name:      "utf8",
		Collation: "utf8_danish_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	204: {
		Id:        204,
		Name:      "utf8",
		Collation: "utf8_lithuanian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	205: {
		Id:        205,
		Name:      "utf8",
		Collation: "utf8_slovak_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	206: {
		Id:        206,
		Name:      "utf8",
		Collation: "utf8_spanish2_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	207: {
		Id:        207,
		Name:      "utf8",
		Collation: "utf8_roman_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	208: {
		Id:        208,
		Name:      "utf8",
		Collation: "utf8_persian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	209: {
		Id:        209,
		Name:      "utf8",
		Collation: "utf8_esperanto_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	210: {
		Id:        210,
		Name:      "utf8",
		Collation: "utf8_hungarian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	211: {
		Id:        211,
		Name:      "utf8",
		Collation: "utf8_sinhala_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	212: {
		Id:        212,
		Name:      "utf8",
		Collation: "utf8_german2_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	213: {
		Id:        213,
		Name:      "utf8",
		Collation: "utf8_croatian_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	214: {
		Id:        214,
		Name:      "utf8",
		Collation: "utf8_unicode_520_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	215: {
		Id:        215,
		Name:      "utf8",
		Collation: "utf8_vietnamese_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	223: {
		Id:        223,
		Name:      "utf8",
		Collation: "utf8_general_mysql500_ci",
		IsDefault: false,
		MaxLen:    3,
	},
	45: {
		Id:        45,
		Name:      "utf8mb4",
		Collation: "utf8mb4_general_ci",
		IsDefault: true,
		MaxLen:    4,
	},
	46: {
		Id:        46,
		Name:      "utf8mb4",
		Collation: "utf8mb4_bin",
		IsDefault: false,
		MaxLen:    4,
	},
	224: {
		Id:        224,
		Name:      "utf8mb4",
		Collation: "utf8mb4_unicode_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	225: {
		Id:        225,
		Name:      "utf8mb4",
		Collation: "utf8mb4_icelandic_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	226: {
		Id:        226,
		Name:      "utf8mb4",
		Collation: "utf8mb4_latvian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	227: {
		Id:        227,
		Name:      "utf8mb4",
		Collation: "utf8mb4_romanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	228: {
		Id:        228,
		Name:      "utf8mb4",
		Collation: "utf8mb4_slovenian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	229: {
		Id:        229,
		Name:      "utf8mb4",
		Collation: "utf8mb4_polish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	230: {
		Id:        230,
		Name:      "utf8mb4",
		Collation: "utf8mb4_estonian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	231: {
		Id:        231,
		Name:      "utf8mb4",
		Collation: "utf8mb4_spanish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	232: {
		Id:        232,
		Name:      "utf8mb4",
		Collation: "utf8mb4_swedish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	233: {
		Id:        233,
		Name:      "utf8mb4",
		Collation: "utf8mb4_turkish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	234: {
		Id:        234,
		Name:      "utf8mb4",
		Collation: "utf8mb4_czech_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	235: {
		Id:        235,
		Name:      "utf8mb4",
		Collation: "utf8mb4_danish_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	236: {
		Id:        236,
		Name:      "utf8mb4",
		Collation: "utf8mb4_lithuanian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	237: {
		Id:        237,
		Name:      "utf8mb4",
		Collation: "utf8mb4_slovak_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	238: {
		Id:        238,
		Name:      "utf8mb4",
		Collation: "utf8mb4_spanish2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	239: {
		Id:        239,
		Name:      "utf8mb4",
		Collation: "utf8mb4_roman_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	240: {
		Id:        240,
		Name:      "utf8mb4",
		Collation: "utf8mb4_persian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	241: {
		Id:        241,
		Name:      "utf8mb4",
		Collation: "utf8mb4_esperanto_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	242: {
		Id:        242,
		Name:      "utf8mb4",
		Collation: "utf8mb4_hungarian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	243: {
		Id:        243,
		Name:      "utf8mb4",
		Collation: "utf8mb4_sinhala_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	244: {
		Id:        244,
		Name:      "utf8mb4",
		Collation: "utf8mb4_german2_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	245: {
		Id:        245,
		Name:      "utf8mb4",
		Collation: "utf8mb4_croatian_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	246: {
		Id:        246,
		Name:      "utf8mb4",
		Collation: "utf8mb4_unicode_520_ci",
		IsDefault: false,
		MaxLen:    4,
	},
	247: {
		Id:        247,
		Name:      "utf8mb4",
		Collation: "utf8mb4_vietnamese_ci",
		IsDefault: false,
		MaxLen:    4,
	},
}

func Lookup(id uint64) *Charset {
	ch, ok := codeToCharsetMap[id]
	if !ok {
		panic(errors.NewFormat("Charset id '%d' not found", id))
	}

	return &ch
}
